// @flow

const actionTypes = {
  GET_OTP_REQUEST: 'GET_OTP_REQUEST',
  GET_OTP_SUCCESS: 'GET_OTP_SUCCESS',
  GET_OTP_FAIL: 'GET_OTP_FAIL',

  LOGIN_OTP_REQUEST: 'LOGIN_OTP_REQUEST',
  LOGIN_OTP_SUCCESS: 'LOGIN_OTP_SUCCESS',
  LOGIN_OTP_FAILED: 'LOGIN_OTP_FAILED',
  REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED',
  LOGOUT: 'LOGOUT',
  REMOVE_TOKEN: 'REMOVE_TOKEN',

  LIST_GRID_DEPOSIT_REQUEST: 'LIST_GRID_DEPOSIT_REQUEST',
  LIST_GRID_DEPOSIT_SUCCESS: 'LIST_GRID_DEPOSIT_SUCCESS',
  LIST_GRID_DEPOSIT_FAILED: 'LIST_GRID_DEPOSIT_FAILED',

  LIST_GRID_DEPOSIT_FILTER_PAGINATE_REQUEST: 'LIST_GRID_DEPOSIT_FILTER_PAGINATE_REQUEST',
  LIST_GRID_DEPOSIT_FILTER_PAGINATE_SUCCESS: 'LIST_GRID_DEPOSIT_FILTER_PAGINATE_SUCCESS',
  LIST_GRID_DEPOSIT_FILTER_PAGINATE_FAILED: 'LIST_GRID_DEPOSIT_FILTER_PAGINATE_FAILED',

  GET_CONFIG_REQUEST: 'GET_CONFIG_REQUEST',
  GET_CONFIG_SUCCESS: 'GET_CONFIG_SUCCESS',
  GET_CONFIG_FAILED: 'GET_CONFIG_FAILED',

  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILED: 'GET_PROFILE_FAILED',

  GET_ORGANIZATION_PROFILE_REQUEST: 'GET_ORGANIZATION_PROFILE_REQUEST',
  GET_ORGANIZATION_PROFILE_SUCCESS: 'GET_ORGANIZATION_PROFILE_SUCCESS',
  GET_ORGANIZATION_PROFILE_FAILED: 'GET_ORGANIZATION_PROFILE_FAILED',

  SAVE_PROFILE_REQUEST: 'SAVE_PROFILE_REQUEST',
  SAVE_PROFILE_SUCCESS: 'SAVE_PROFILE_SUCCESS',
  SAVE_PROFILE_FAILED: 'SAVE_PROFILE_FAILED',

  SAVE_ORGANIZATION_PROFILE_REQUEST: 'SAVE_ORGANIZATION_PROFILE_REQUEST',
  SAVE_ORGANIZATION_PROFILE_SUCCESS: 'SAVE_ORGANIZATION_PROFILE_SUCCESS',
  SAVE_ORGANIZATION_PROFILE_FAILED: 'SAVE_ORGANIZATION_PROFILE_FAILED',

  GET_INSTALLMENT_REQUEST: 'GET_INSTALLMENT_REQUEST',
  GET_INSTALLMENT_SUCCESS: 'GET_INSTALLMENT_SUCCESS',
  GET_INSTALLMENT_FAILED: 'GET_INSTALLMENT_FAILED',

  GET_INSTALLMENT_PAGINATION_REQUEST: 'GET_INSTALLMENT_PAGINATION_REQUEST',
  GET_INSTALLMENT_PAGINATION_SUCCESS: 'GET_INSTALLMENT_PAGINATION_SUCCESS',
  GET_INSTALLMENT_PAGINATION_FAILED: 'GET_INSTALLMENT_PAGINATION_FAILED',

  GET_INSTALLMENT_FILTER_REQUEST: 'GET_INSTALLMENT_FILTER_REQUEST',
  GET_INSTALLMENT_FILTER_SUCCESS: 'GET_INSTALLMENT_FILTER_SUCCESS',
  GET_INSTALLMENT_FILTER_FAILED: 'GET_INSTALLMENT_FILTER_FAILED',

  GET_ORGANIZATION_INSTALLMENT_REQUEST: 'GET_ORGANIZATION_INSTALLMENT_REQUEST',
  GET_ORGANIZATION_INSTALLMENT_SUCCESS: 'GET_ORGANIZATION_INSTALLMENT_SUCCESS',
  GET_ORGANIZATION_INSTALLMENT_FAILED: 'GET_ORGANIZATION_INSTALLMENT_FAILED',
  GET_ORGANIZATION_INSTALLMENT_PAGINATE_REQUEST: 'GET_ORGANIZATION_INSTALLMENT_PAGINATE_REQUEST',
  GET_ORGANIZATION_INSTALLMENT_PAGINATE_SUCCESS: 'GET_ORGANIZATION_INSTALLMENT_PAGINATE_SUCCESS',
  GET_ORGANIZATION_INSTALLMENT_PAGINATE_FAILED: 'GET_ORGANIZATION_INSTALLMENT_PAGINATE_FAILED',

  FILTER_ORGANIZATION_INSTALLMENT_REQUEST: 'FILTER_ORGANIZATION_INSTALLMENT_REQUEST',
  FILTER_ORGANIZATION_INSTALLMENT_SUCCESS: 'FILTER_ORGANIZATION_INSTALLMENT_SUCCESS',
  FILTER_ORGANIZATION_INSTALLMENT_FAILED: 'FILTER_ORGANIZATION_INSTALLMENT_FAILED',

  FILTER_ORGANIZATION_INSTALLMENT_PAGING_REQUEST: 'FILTER_ORGANIZATION_INSTALLMENT_PAGING_REQUEST',
  FILTER_ORGANIZATION_INSTALLMENT_PAGING_SUCCESS: 'FILTER_ORGANIZATION_INSTALLMENT_PAGING_SUCCESS',
  FILTER_ORGANIZATION_INSTALLMENT_PAGING_FAILED: 'FILTER_ORGANIZATION_INSTALLMENT_PAGING_FAILED',

  PAY_ONLINE_REQUEST: 'PAY_ONLINE_REQUEST',
  PAY_ONLINE_SUCCESS: 'PAY_ONLINE_SUCCESS',
  PAY_ONLINE_FAILED: 'PAY_ONLINE_FAILED',

  PAY_OFFLINE_REQUEST: 'PAY_OFFLINE_REQUEST',
  PAY_OFFLINE_SUCCESS: 'PAY_OFFLINE_SUCCESS',
  PAY_OFFLINE_FAILED: 'PAY_OFFLINE_FAILED',

  POST_INSTALLMENT_REQUEST: 'POST_INSTALLMENT_REQUEST',
  POST_INSTALLMENT_SUCCESS: 'POST_INSTALLMENT_SUCCESS',
  POST_INSTALLMENT_FAILED: 'POST_INSTALLMENT_FAILED',

  GET_PAYMENT_REPORT_REQUEST: 'GET_PAYMENT_REPORT_REQUEST',
  GET_PAYMENT_REPORT_SUCCESS: 'GET_PAYMENT_REPORT_SUCCESS',
  GET_PAYMENT_REPORT_FAILED: 'GET_PAYMENT_REPORT_FAILED',

  GET_PAYMENT_REPORT_PAGINATE_REQUEST: 'GET_PAYMENT_REPORT_PAGINATE_REQUEST',
  GET_PAYMENT_REPORT_PAGINATE_SUCCESS: 'GET_PAYMENT_REPORT_PAGINATE_SUCCESS',
  GET_PAYMENT_REPORT_PAGINATE_FAILED: 'GET_PAYMENT_REPORT_PAGINATE_FAILED',

  GET_PAYMENT_REPORT_FILTER_REQUEST: 'GET_PAYMENT_REPORT_FILTER_REQUEST',
  GET_PAYMENT_REPORT_FILTER_SUCCESS: 'GET_PAYMENT_REPORT_FILTER_SUCCESS',
  GET_PAYMENT_REPORT_FILTER_FAILED: 'GET_PAYMENT_REPORT_FILTER_FAILED',

  GET_PAYMENT_REPORT_FILTER_PAGING_REQUEST: 'GET_PAYMENT_REPORT_FILTER_PAGING_REQUEST',
  GET_PAYMENT_REPORT_FILTER_PAGING_SUCCESS: 'GET_PAYMENT_REPORT_FILTER_PAGING_SUCCESS',
  GET_PAYMENT_REPORT_FILTER_PAGING_FAILED: 'GET_PAYMENT_REPORT_FILTER_PAGING_FAILED',

  GET_INSTALLMENT_REPORT_REQUEST: 'GET_INSTALLMENT_REPORT_REQUEST',
  GET_INSTALLMENT_REPORT_SUCCESS: 'GET_INSTALLMENT_REPORT_SUCCESS',
  GET_INSTALLMENT_REPORT_FAILED: 'GET_INSTALLMENT_REPORT_FAILED',

  GET_INSTALLMENT_REPORT_PAGINATION_REQUEST: 'GET_INSTALLMENT_REPORT_PAGINATION_REQUEST',
  GET_INSTALLMENT_REPORT_PAGINATION_SUCCESS: 'GET_INSTALLMENT_REPORT_PAGINATION_SUCCESS',
  GET_INSTALLMENT_REPORT_PAGINATION_FAILED: 'GET_INSTALLMENT_REPORT_PAGINATION_FAILED',

  GET_INSTALLMENT_REPORT_FILTER_REQUEST: 'GET_INSTALLMENT_REPORT_FILTER_REQUEST',
  GET_INSTALLMENT_REPORT_FILTER_SUCCESS: 'GET_INSTALLMENT_REPORT_FILTER_SUCCESS',
  GET_INSTALLMENT_REPORT_FILTER_FAILED: 'GET_INSTALLMENT_REPORT_FILTER_FAILED',

  GET_INSTALLMENT_REPORT_FILTER_PAGING_REQUEST: 'GET_INSTALLMENT_REPORT_FILTER_PAGING_REQUEST',
  GET_INSTALLMENT_REPORT_FILTER_PAGING_SUCCESS: 'GET_INSTALLMENT_REPORT_FILTER_PAGING_SUCCESS',
  GET_INSTALLMENT_REPORT_FILTER_PAGING_FAILED: 'GET_INSTALLMENT_REPORT_FILTER_PAGING_FAILED',

  GET_PURCHASE_REPORT_REQUEST: 'GET_PURCHASE_REPORT_REQUEST',
  GET_PURCHASE_REPORT_SUCCESS: 'GET_PURCHASE_REPORT_SUCCESS',
  GET_PURCHASE_REPORT_FAILED: 'GET_PURCHASE_REPORT_FAILED',

  GET_PURCHASE_REPORT_REQUEST_PAGINATE: 'GET_PURCHASE_REPORT_REQUEST_PAGINATE',
  GET_PURCHASE_REPORT_SUCCESS_PAGINATE: 'GET_PURCHASE_REPORT_SUCCESS_PAGINATE',
  GET_PURCHASE_REPORT_FAILED_PAGINATE: 'GET_PURCHASE_REPORT_FAILED_PAGINATE',

  GET_PURCHASE_REPORT_FILTER_REQUEST: 'GET_PURCHASE_REPORT_FILTER_REQUEST',
  GET_PURCHASE_REPORT_FILTER_SUCCESS: 'GET_PURCHASE_REPORT_FILTER_SUCCESS',
  GET_PURCHASE_REPORT_FILTER_FAILED: 'GET_PURCHASE_REPORT_FILTER_FAILED',

  GET_PURCHASE_REPORT_FILTER_PAGING_REQUEST: 'GET_PURCHASE_REPORT_FILTER_PAGING_REQUEST',
  GET_PURCHASE_REPORT_FILTER_PAGING_SUCCESS: 'GET_PURCHASE_REPORT_FILTER_PAGING_SUCCESS',
  GET_PURCHASE_REPORT_FILTER_PAGING_FAILED: 'GET_PURCHASE_REPORT_FILTER_PAGING_FAILED',

  SEND_EMAIL_OTP_REQUEST: 'SEND_EMAIL_OTP_REQUEST',
  SEND_EMAIL_OTP_SUCCESS: 'SEND_EMAIL_OTP_SUCCESS',
  SEND_EMAIL_OTP_FAILED: 'SEND_EMAIL_OTP_FAILED',

  VERIFY_EMAIL_REQUEST: 'VERIFY_EMAIL_REQUEST',
  VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_FAILED: 'VERIFY_EMAIL_FAILED',

  SAVE_PROFILE_PICTURE_REQUEST: 'SAVE_PROFILE_PICTURE_REQUEST',
  SAVE_PROFILE_PICTURE_SUCCESS: 'SAVE_PROFILE_PICTURE_SUCCESS',
  SAVE_PROFILE_PICTURE_FAILED: 'SAVE_PROFILE_PICTURE_FAILED',

  GET_DASHBOARD_REQUEST: 'GET_DASHBOARD_REQUEST',
  GET_DASHBOARD_SUCCESS: 'GET_DASHBOARD_SUCCESS',
  GET_DASHBOARD_FAILED: 'GET_DASHBOARD_FAILED',

  GET_PURCHASES_REQUEST: 'GET_PURCHASES_REQUEST',
  GET_PURCHASES_SUCCESS: 'GET_PURCHASES_SUCCESS',
  GET_PURCHASES_FAILED: 'GET_PURCHASES_FAILED',

  PAY_PURCHASES_REQUEST: 'PAY_PURCHASES_REQUEST',
  PAY_PURCHASES_SUCCESS: 'PAY_PURCHASES_SUCCESS',
  PAY_PURCHASES_FAILED: 'PAY_PURCHASES_FAILED',

  PURCHASES_DESCRIPTION_REQUEST: 'PURCHASES_DESCRIPTION_REQUEST',
  PURCHASES_DESCRIPTION_SUCCESS: 'PURCHASES_DESCRIPTION_SUCCESS',
  PURCHASES_DESCRIPTION_FAILED: 'PURCHASES_DESCRIPTION_FAILED',

  SET_EDITED_VALUE: 'SET_EDITED_VALUE',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',

  GET_LIST_CARD_MANAGE_REQUEST: 'GET_LIST_CARD_MANAGE_REQUEST',
  GET_LIST_CARD_MANAGE_SUCCESS: 'GET_LIST_CARD_MANAGE_SUCCESS',
  GET_LIST_CARD_MANAGE_FAILED: 'GET_LIST_CARD_MANAGE_FAILED',

  GET_LIST_CARD_MANAGE_PAGINATE_REQUEST: 'GET_LIST_CARD_MANAGE_PAGINATE_REQUEST',
  GET_LIST_CARD_MANAGE_PAGINATE_SUCCESS: 'GET_LIST_CARD_MANAGE_PAGINATE_SUCCESS',
  GET_LIST_CARD_MANAGE_PAGINATE_FAILED: 'GET_LIST_CARD_MANAGE_PAGINATE_FAILED',

  GET_LIST_CARD_MANAGE_PAGINATE_COMP_REQUEST: 'GET_LIST_CARD_MANAGE_PAGINATE_COMP_REQUEST',
  GET_LIST_CARD_MANAGE_PAGINATE_COMP_SUCCESS: 'GET_LIST_CARD_MANAGE_PAGINATE_COMP_SUCCESS',
  GET_LIST_CARD_MANAGE_PAGINATE_COMP_FAILED: 'GET_LIST_CARD_MANAGE_PAGINATE_COMP_FAILED',

  GET_CARD_MANAGE_FILTER_REQUEST: 'GET_CARD_MANAGE_FILTER_REQUEST',
  GET_CARD_MANAGE_FILTER_SUCCESS: 'GET_CARD_MANAGE_FILTER_SUCCESS',
  GET_CARD_MANAGE_FILTER_FAILED: 'GET_CARD_MANAGE_FILTER_FAILED',

  GET_CARD_MANAGE_FILTER_PAGING_REQUEST: 'GET_CARD_MANAGE_FILTER_PAGING_REQUEST',
  GET_CARD_MANAGE_FILTER_PAGING_SUCCESS: 'GET_CARD_MANAGE_FILTER_PAGING_SUCCESS',
  GET_CARD_MANAGE_FILTER_PAGING_FAILED: 'GET_CARD_MANAGE_FILTER_PAGING_FAILED',

  GET_CARD_MANAGE_FILTER_PAGINATION_REQUEST: 'GET_CARD_MANAGE_FILTER_PAGINATION_REQUEST',
  GET_CARD_MANAGE_FILTER_PAGINATION_SUCCESS: 'GET_CARD_MANAGE_FILTER_PAGINATION_SUCCESS',
  GET_CARD_MANAGE_FILTER_PAGINATION_FAILED: 'GET_CARD_MANAGE_FILTER_PAGINATION_FAILED',

  SEARCH_BY_NATIONAL_CODE_REQUEST: 'SEARCH_BY_NATIONAL_CODE_REQUEST',
  SEARCH_BY_NATIONAL_CODE_SUCCESS: 'SEARCH_BY_NATIONAL_CODE_SUCCESS',
  SEARCH_BY_NATIONAL_CODE_FAILED: 'SEARCH_BY_NATIONAL_CODE_FAILED',

  SEARCH_BY_NATIONAL_CODE_MERCHANT_REQUEST: 'SEARCH_BY_NATIONAL_CODE_MERCHANT_REQUEST',
  SEARCH_BY_NATIONAL_CODE_MERCHANT_SUCCESS: 'SEARCH_BY_NATIONAL_CODE_MERCHANT_SUCCESS',
  SEARCH_BY_NATIONAL_CODE_MERCHANT_FAILED: 'SEARCH_BY_NATIONAL_CODE_MERCHANT_FAILED',

  ADD_SINGLE_CARD_REQUEST: 'ADD_SINGLE_CARD_REQUEST',
  ADD_SINGLE_CARD_SUCCESS: 'ADD_SINGLE_CARD_SUCCESS',
  ADD_SINGLE_CARD_FAILED: 'ADD_SINGLE_CARD_FAILED',

  GET_LIST_EDIT_CARD_GROUP_MANAGE_REQUEST: 'GET_LIST_EDIT_CARD_GROUP_MANAGE_REQUEST',
  GET_LIST_EDIT_CARD_GROUP_MANAGE_SUCCESS: 'GET_LIST_EDIT_CARD_GROUP_MANAGE_SUCCESS',
  GET_LIST_EDIT_CARD_GROUP_MANAGE_FAILED: 'GET_LIST_EDIT_CARD_GROUP_MANAGE_FAILED',

  SUBMIT_EDIT_GROUP_CREDIT_REQUEST: 'SUBMIT_EDIT_GROUP_CREDIT_REQUEST',
  SUBMIT_EDIT_GROUP_CREDIT_SUCCESS: 'SUBMIT_EDIT_GROUP_CREDIT_SUCCESS',
  SUBMIT_EDIT_GROUP_CREDIT_FAILED: 'SUBMIT_EDIT_GROUP_CREDIT_FAILED',

  SUBMIT_EDIT_GROUP_STATE_REQUEST: 'SUBMIT_EDIT_GROUP_STATE_REQUEST',
  SUBMIT_EDIT_GROUP_STATE_SUCCESS: 'SUBMIT_EDIT_GROUP_STATE_SUCCESS',
  SUBMIT_EDIT_GROUP_STATE_FAILED: 'SUBMIT_EDIT_GROUP_STATE_FAILED',

  SUBMIT_STATE_CARD_REQUEST: 'SUBMIT_STATE_CARD_REQUEST',
  SUBMIT_STATE_CARD_SUCCESS: 'SUBMIT_STATE_CARD_SUCCESS',
  SUBMIT_STATE_CARD_FAILED: 'SUBMIT_STATE_CARD_FAILED',

  SUBMIT_CREDIT_GROUP_REQUEST: 'SUBMIT_CREDIT_GROUP_REQUEST',
  SUBMIT_CREDIT_GROUP_SUCCESS: 'SUBMIT_CREDIT_GROUP_SUCCESS',
  SUBMIT_CREDIT_GROUP_FAILED: 'SUBMIT_CREDIT_GROUP_FAILED',

  DELETE_ROW_CARD_MANAGE_REQUEST: 'DELETE_ROW_CARD_MANAGE_REQUEST',
  DELETE_ROW_CARD_MANAGE_SUCCESS: 'DELETE_ROW_CARD_MANAGE_SUCCESS',
  DELETE_ROW_CARD_MANAGE_FAILED: 'DELETE_ROW_CARD_MANAGE_FAILED',

  DELETE_EMPLOYEE_PROFILE_REQUEST: 'DELETE_EMPLOYEE_PROFILE_REQUEST',
  DELETE_EMPLOYEE_PROFILE_SUCCESS: 'DELETE_EMPLOYEE_PROFILE_SUCCESS',
  DELETE_EMPLOYEE_PROFILE_FAILED: 'DELETE_EMPLOYEE_PROFILE_FAILED',

  GET_LIST_GROUP_CARD_MANAGE_REQUEST: 'GET_LIST_GROUP_CARD_MANAGE_REQUEST',
  GET_LIST_GROUP_CARD_MANAGE_SUCCESS: 'GET_LIST_GROUP_CARD_MANAGE_SUCCESS',
  GET_LIST_GROUP_CARD_MANAGE_FAILED: 'GET_LIST_GROUP_CARD_MANAGE_FAILED',

  GET_EDIT_LIST_GROUP_CARD_MANAGE_REQUEST: 'GET_EDIT_LIST_GROUP_CARD_MANAGE_REQUEST',
  GET_EDIT_LIST_GROUP_CARD_MANAGE_SUCCESS: 'GET_EDIT_LIST_GROUP_CARD_MANAGE_SUCCESS',
  GET_EDIT_LIST_GROUP_CARD_MANAGE_FAILED: 'GET_EDIT_LIST_GROUP_CARD_MANAGE_FAILED',

  GET_LIST_GROUP_CARD_MANAGE_WORKFLOW_REQUEST: 'GET_LIST_GROUP_CARD_MANAGE_WORKFLOW_REQUEST',
  GET_LIST_GROUP_CARD_MANAGE_WORKFLOW_SUCCESS: 'GET_LIST_GROUP_CARD_MANAGE_WORKFLOW_SUCCESS',
  GET_LIST_GROUP_CARD_MANAGE_WORKFLOW_FAILED: 'GET_LIST_GROUP_CARD_MANAGE_WORKFLOW_FAILED',

  GET_EMPLOYEE_REQUEST: 'GET_EMPLOYEE_REQUEST',
  GET_EMPLOYEE_SUCCESS: 'GET_EMPLOYEE_SUCCESS',
  GET_EMPLOYEE_FAILED: 'GET_EMPLOYEE_FAILED',

  GET_EMPLOYEE_PAGINATE_REQUEST: 'GET_EMPLOYEE_PAGINATE_REQUEST',
  GET_EMPLOYEE_PAGINATE_SUCCESS: 'GET_EMPLOYEE_PAGINATE_SUCCESS',
  GET_EMPLOYEE_PAGINATE_FAILED: 'GET_EMPLOYEE_PAGINATE_FAILED',

  GET_EMPLOYEE_FILTER_REQUEST: 'GET_EMPLOYEE_FILTER_REQUEST',
  GET_EMPLOYEE_FILTER_SUCCESS: 'GET_EMPLOYEE_FILTER_SUCCESS',
  GET_EMPLOYEE_FILTER_FAILED: 'GET_EMPLOYEE_FILTER_FAILED',

  GET_EMPLOYEE_FILTER_PAGING_REQUEST: 'GET_EMPLOYEE_FILTER_PAGING_REQUEST',
  GET_EMPLOYEE_FILTER_PAGING_SUCCESS: 'GET_EMPLOYEE_FILTER_PAGING_SUCCESS',
  GET_EMPLOYEE_FILTER_PAGING_FAILED: 'GET_EMPLOYEE_FILTER_PAGING_FAILED',

  ADD_SINGLE_EMPLOYEE_REQUEST: 'ADD_SINGLE_EMPLOYEE_REQUEST',
  ADD_SINGLE_EMPLOYEE_SUCCESS: 'ADD_SINGLE_EMPLOYEE_SUCCESS',
  ADD_SINGLE_EMPLOYEE_FAILED: 'ADD_SINGLE_EMPLOYEE_FAILED',

  ADD_MULTIPLE_CARD_REQUEST: 'ADD_MULTIPLE_CARD_REQUEST',
  ADD_MULTIPLE_CARD_SUCCESS: 'ADD_MULTIPLE_CARD_SUCCESS',
  ADD_MULTIPLE_CARD_FAILED: 'ADD_MULTIPLE_CARD_FAILED',

  EDIT_SINGLE_EMPLOYEE_REQUEST: 'EDIT_SINGLE_EMPLOYEE_REQUEST',
  EDIT_SINGLE_EMPLOYEE_SUCCESS: 'EDIT_SINGLE_EMPLOYEE_SUCCESS',
  EDIT_SINGLE_EMPLOYEE_FAILED: 'EDIT_SINGLE_EMPLOYEE_FAILED',

  SEARCH_NATIONAL_CODE_REQUEST: 'SEARCH_NATIONAL_CODE_REQUEST',
  SEARCH_NATIONAL_CODE_SUCCESS: 'SEARCH_NATIONAL_CODE_SUCCESS',
  SEARCH_NATIONAL_CODE_FAILED: 'SEARCH_NATIONAL_CODE_FAILED',

  SEARCH_NATIONAL_CODE_COMPANY_REQUEST: 'SEARCH_NATIONAL_CODE_COMPANY_REQUEST',
  SEARCH_NATIONAL_CODE_COMPANY_SUCCESS: 'SEARCH_NATIONAL_CODE_COMPANY_SUCCESS',
  SEARCH_NATIONAL_CODE_COMPANY_FAILED: 'SEARCH_NATIONAL_CODE_COMPANY_FAILED',

  ADD_CARD_REQUEST: 'ADD_CARD_REQUEST',
  ADD_CARD_SUCCESS: 'ADD_CARD_SUCCESS',
  ADD_CARD_FAILED: 'ADD_CARD_FAILED',

  SEND_VERIFICATION_CODE_REQUEST: 'SEND_VERIFICATION_CODE_REQUEST',
  SEND_VERIFICATION_CODE_SUCCESS: 'SEND_VERIFICATION_CODE_SUCCESS',
  SEND_VERIFICATION_CODE_FAILED: 'SEND_VERIFICATION_CODE_FAILED',

  EDIT_CARD_STATUS_REQUEST: 'EDIT_CARD_STATUS_REQUEST',
  EDIT_CARD_STATUS_SUCCESS: 'EDIT_CARD_STATUS_SUCCESS',
  EDIT_CARD_STATUS_FAILED: 'EDIT_CARD_STATUS_FAILED',

  EDIT_CARD_CREDIT_REQUEST: 'EDIT_CARD_CREDIT_REQUEST',
  EDIT_CARD_CREDIT_SUCCESS: 'EDIT_CARD_CREDIT_SUCCESS',
  EDIT_CARD_CREDIT_FAILED: 'EDIT_CARD_CREDIT_FAILED',

  SEND_EMAIL_ACCOUNT_REQUEST: 'SEND_EMAIL_ACCOUNT_REQUEST',
  SEND_EMAIL_ACCOUNT_SUCCESS: 'SEND_EMAIL_ACCOUNT_SUCCESS',
  SEND_EMAIL_ACCOUNT_FAILED: 'SEND_EMAIL_ACCOUNT_FAILED',

  VERIFY_EMAIL_ACCOUNT_REQUEST: 'VERIFY_EMAIL_ACCOUNT_REQUEST',
  VERIFY_EMAIL_ACCOUNT_SUCCESS: 'VERIFY_EMAIL_ACCOUNT_SUCCESS',
  VERIFY_EMAIL_ACCOUNT_FAILED: 'VERIFY_EMAIL_ACCOUNT_FAILED',

  GET_ACCOUNT_REQUEST: 'GET_ACCOUNT_REQUEST',
  GET_ACCOUNT_SUCCESS: 'GET_ACCOUNT_SUCCESS',
  GET_ACCOUNT_FAILED: 'GET_ACCOUNT_FAILED',

  SAVE_ACCOUNT_REQUEST: 'SAVE_ACCOUNT_REQUEST',
  SAVE_ACCOUNT_SUCCESS: 'SAVE_ACCOUNT_SUCCESS',
  SAVE_ACCOUNT_FAILED: 'SAVE_ACCOUNT_FAILED',

  GET_GRID_CONTRACT_REQUEST: 'GET_GRID_CONTRACT_REQUEST',
  GET_GRID_CONTRACT_SUCCESS: 'GET_GRID_CONTRACT_SUCCESS',
  GET_GRID_CONTRACT_FAILED: 'GET_GRID_CONTRACT_FAILED',
  GET_GRID_CONTRACT_PAGINATE_REQUEST: 'GET_GRID_CONTRACT_PAGINATE_REQUEST',
  GET_GRID_CONTRACT_PAGINATE_SUCCESS: 'GET_GRID_CONTRACT_PAGINATE_SUCCESS',
  GET_GRID_CONTRACT_PAGINATE_FAILED: 'GET_GRID_CONTRACT_PAGINATE_FAILED',

  EDIT_CONTRACT_REQUEST: 'EDIT_CONTRACT_REQUEST',
  EDIT_CONTRACT_SUCCESS: 'EDIT_CONTRACT_SUCCESS',
  EDIT_CONTRACT_FAILED: 'EDIT_CONTRACT_FAILED',

  ADD_CONTRACT_REQUEST: 'ADD_CONTRACT_REQUEST',
  ADD_CONTRACT_SUCCESS: 'ADD_CONTRACT_SUCCESS',
  ADD_CONTRACT_FAILED: 'ADD_CONTRACT_FAILED',

  EDIT_STATE_CONTRACT_REQUEST: 'EDIT_STATE_CONTRACT_REQUEST',
  EDIT_STATE_CONTRACT_SUCCESS: 'EDIT_STATE_CONTRACT_SUCCESS',
  EDIT_STATE_CONTRACT_FAILED: 'EDIT_STATE_CONTRACT_FAILED',

  ACCEPT_STATE_CONTRACT_REQUEST: 'ACCEPT_STATE_CONTRACT_REQUEST',
  ACCEPT_STATE_CONTRACT_SUCCESS: 'ACCEPT_STATE_CONTRACT_SUCCESS',
  ACCEPT_STATE_CONTRACT_FAILED: 'ACCEPT_STATE_CONTRACT_FAILED',

  DELETE_CONTRACT_REQUEST: 'DELETE_CONTRACT_REQUEST',
  DELETE_CONTRACT_SUCCESS: 'DELETE_CONTRACT_SUCCESS',
  DELETE_CONTRACT_FAILED: 'DELETE_CONTRACT_FAILED',

  LIST_GRID_DEPOSIT_PAGINATE_REQUEST: 'LIST_GRID_DEPOSIT_PAGINATE_REQUEST',
  LIST_GRID_DEPOSIT_PAGINATE_SUCCESS: 'LIST_GRID_DEPOSIT_PAGINATE_SUCCESS',
  LIST_GRID_DEPOSIT_PAGINATE_FAILED: 'LIST_GRID_DEPOSIT_PAGINATE_FAILED',

  LIST_GRID_COMPANY_DEPOSIT_REQUEST: 'LIST_GRID_COMPANY_DEPOSIT_REQUEST',
  LIST_GRID_COMPANY_DEPOSIT_SUCCESS: 'LIST_GRID_COMPANY_DEPOSIT_SUCCESS',
  LIST_GRID_COMPANY_DEPOSIT_FAILED: 'LIST_GRID_COMPANY_DEPOSIT_FAILED',

  LIST_GRID_COMPANY_DEPOSIT_PAGINATE_REQUEST: 'LIST_GRID_COMPANY_DEPOSIT_PAGINATE_REQUEST',
  LIST_GRID_COMPANY_DEPOSIT_PAGINATE_SUCCESS: 'LIST_GRID_COMPANY_DEPOSIT_PAGINATE_SUCCESS',
  LIST_GRID_COMPANY_DEPOSIT_PAGINATE_FAILED: 'LIST_GRID_COMPANY_DEPOSIT_PAGINATE_FAILED',

  LIST_FILTER_COMPANY_DEPOSIT_REQUEST: 'LIST_GRID_COMPANY_DEPOSIT_REQUEST',
  LIST_FILTER_COMPANY_DEPOSIT_SUCCESS: 'LIST_GRID_COMPANY_DEPOSIT_SUCCESS',
  LIST_FILTER_COMPANY_DEPOSIT_FAILED: 'LIST_GRID_COMPANY_DEPOSIT_FAILED',

  LIST_FILTER_COMPANY_DEPOSIT_PAGINATE_REQUEST: 'LIST_FILTER_COMPANY_DEPOSIT_PAGINATE_REQUEST',
  LIST_FILTER_COMPANY_DEPOSIT_PAGINATE_SUCCESS: 'LIST_FILTER_COMPANY_DEPOSIT_PAGINATE_SUCCESS',
  LIST_FILTER_COMPANY_DEPOSIT_PAGINATE_FAILED: 'LIST_FILTER_COMPANY_DEPOSIT_PAGINATE_FAILED',

  LIST_COMPANY_PURCHASE_REQUEST: 'LIST_COMPANY_PURCHASE_REQUEST',
  LIST_COMPANY_PURCHASE_SUCCESS: 'LIST_COMPANY_PURCHASE_SUCCESS',
  LIST_COMPANY_PURCHASE_FAILED: 'LIST_COMPANY_PURCHASE_FAILED',

  LIST_COMPANY_PURCHASE_PAGINATE_REQUEST: 'LIST_COMPANY_PURCHASE_PAGINATE_REQUEST',
  LIST_COMPANY_PURCHASE_PAGINATE_SUCCESS: 'LIST_COMPANY_PURCHASE_PAGINATE_SUCCESS',
  LIST_COMPANY_PURCHASE_PAGINATE_FAILED: 'LIST_COMPANY_PURCHASE_PAGINATE_FAILED',

  LIST_FILTER_COMPANY_PURCHASE_REQUEST: 'LIST_FILTER_COMPANY_PURCHASE_REQUEST',
  LIST_FILTER_COMPANY_PURCHASE_SUCCESS: 'LIST_FILTER_COMPANY_PURCHASE_SUCCESS',
  LIST_FILTER_COMPANY_PURCHASE_FAILED: 'LIST_FILTER_COMPANY_PURCHASE_FAILED',

  LIST_FILTER_COMPANY_PURCHASE_PAGINATION_REQUEST: 'LIST_FILTER_COMPANY_PURCHASE_PAGINATION_REQUEST',
  LIST_FILTER_COMPANY_PURCHASE_PAGINATION_SUCCESS: 'LIST_FILTER_COMPANY_PURCHASE_PAGINATION_SUCCESS',
  LIST_FILTER_COMPANY_PURCHASE_PAGINATION_FAILED: 'LIST_FILTER_COMPANY_PURCHASE_PAGINATION_FAILED',

  CHANGE_ROLE_REQUEST: 'CHANGE_ROLE_REQUEST',
  CHANGE_ROLE_SUCCESS: 'CHANGE_ROLE_SUCCESS',
  CHANGE_ROLE_FAILED: 'CHANGE_ROLE_FAILED',

  GET_ORGANIZATION_DASHBOARD_REQUEST: 'GET_ORGANIZATION_DASHBOARD_REQUEST',
  GET_ORGANIZATION_DASHBOARD_SUCCESS: 'GET_ORGANIZATION_DASHBOARD_SUCCESS',
  GET_ORGANIZATION_DASHBOARD_FAILED: 'GET_ORGANIZATION_DASHBOARD_FAILED',

  POST_RETURN_PAYMENT_REQUEST: 'POST_RETURN_PAYMENT_REQUEST',
  POST_RETURN_PAYMENT_SUCCESS: 'POST_RETURN_PAYMENT_SUCCESS',
  POST_RETURN_PAYMENT_FAILED: 'POST_RETURN_PAYMENT_FAILED',

  ADD_CREDIT_GROUP_REQUEST: 'ADD_CREDIT_GROUP_REQUEST',
  ADD_CREDIT_GROUP_SUCCESS: 'ADD_CREDIT_GROUP_SUCCESS',
  ADD_CREDIT_GROUP_FAILED: 'ADD_CREDIT_GROUP_FAILED',

  EDIT_CREDIT_GROUP_REQUEST: 'EDIT_CREDIT_GROUP_REQUEST',
  EDIT_CREDIT_GROUP_SUCCESS: 'EDIT_CREDIT_GROUP_SUCCESS',
  EDIT_CREDIT_GROUP_FAILED: 'EDIT_CREDIT_GROUP_FAILED',

  DELETE_CREDIT_GROUP_REQUEST: 'DELETE_CREDIT_GROUP_REQUEST',
  DELETE_CREDIT_GROUP_SUCCESS: 'DELETE_CREDIT_GROUP_SUCCESS',
  DELETE_CREDIT_GROUP_FAILED: 'DELETE_CREDIT_GROUP_FAILED',

  GET_PROFILE_MERCHANT_REQUEST: 'GET_PROFILE_MERCHANT_REQUEST',
  GET_PROFILE_MERCHANT_SUCCESS: 'GET_PROFILE_MERCHANT_SUCCESS',
  GET_PROFILE_MERCHANT_FAILED: 'GET_PROFILE_MERCHANT_FAILED',

  GET_DASHBOARD_MERCHANT_REQUEST: 'GET_DASHBOARD_MERCHANT_REQUEST',
  GET_DASHBOARD_MERCHANT_SUCCESS: 'GET_DASHBOARD_MERCHANT_SUCCESS',
  GET_DASHBOARD_MERCHANT_FAILED: 'GET_DASHBOARD_MERCHANT_FAILED',

  GET_DASHBOARD_PRICE_CHART_REQUEST: 'GET_DASHBOARD_PRICE_CHART_REQUEST',
  GET_DASHBOARD_PRICE_CHART_SUCCESS: 'GET_DASHBOARD_PRICE_CHART_SUCCESS',
  GET_DASHBOARD_PRICE_CHART_FAILED: 'GET_DASHBOARD_PRICE_CHART_FAILED',

  GET_DASHBOARD_COUNT_CHART_REQUEST: 'GET_DASHBOARD_COUNT_CHART_REQUEST',
  GET_DASHBOARD_COUNT_CHART_SUCCESS: 'GET_DASHBOARD_COUNT_CHART_SUCCESS',
  GET_DASHBOARD_COUNT_CHART_FAILED: 'GET_DASHBOARD_COUNT_CHART_FAILED',

  SAVE_PROFILE_MERCHANT_REQUEST: 'SAVE_PROFILE_MERCHANT_REQUEST',
  SAVE_PROFILE_MERCHANT_SUCCESS: 'SAVE_PROFILE_MERCHANT_SUCCESS',
  SAVE_PROFILE_MERCHANT_FAILED: 'SAVE_PROFILE_MERCHANT_FAILED',

  GET_INSTALLMENT_MERCHANT_REQUEST: 'GET_INSTALLMENT_MERCHANT_REQUEST',
  GET_INSTALLMENT_MERCHANT_SUCCESS: 'GET_INSTALLMENT_MERCHANT_SUCCESS',
  GET_INSTALLMENT_MERCHANT_FAILED: 'GET_INSTALLMENT_MERCHANT_FAILED',

  GET_INSTALLMENT_MERCHANT_FILTER_REQUEST: 'GET_INSTALLMENT_MERCHANT_FILTER_REQUEST',
  GET_INSTALLMENT_MERCHANT_FILTER_SUCCESS: 'GET_INSTALLMENT_MERCHANT_FILTER_SUCCESS',
  GET_INSTALLMENT_MERCHANT_FILTER_FAILED: 'GET_INSTALLMENT_MERCHANT_FILTER_FAILED',

  GET_INSTALLMENT_MERCHANT_PAGINATE_REQUEST: 'GET_INSTALLMENT_MERCHANT_PAGINATE_REQUEST',
  GET_INSTALLMENT_MERCHANT_PAGINATE_SUCCESS: 'GET_INSTALLMENT_MERCHANT_PAGINATE_SUCCESS',
  GET_INSTALLMENT_MERCHANT_PAGINATE_FAILED: 'GET_INSTALLMENT_MERCHANT_PAGINATE_FAILED',

  GET_INSTALLMENT_MERCHANT_PAGINATE_FILTER_REQUEST: 'GET_INSTALLMENT_MERCHANT_PAGINATE_FILTER_REQUEST',
  GET_INSTALLMENT_MERCHANT_PAGINATE_FILTER_SUCCESS: 'GET_INSTALLMENT_MERCHANT_PAGINATE_FILTER_SUCCESS',
  GET_INSTALLMENT_MERCHANT_PAGINATE_FILTER_FAILED: 'GET_INSTALLMENT_MERCHANT_PAGINATE_FILTER_FAILED',

  GET_PROMOTIONS_MERCHANT_REQUEST: 'GET_PROMOTIONS_MERCHANT_REQUEST',
  GET_PROMOTIONS_MERCHANT_SUCCESS: 'GET_PROMOTIONS_MERCHANT_SUCCESS',
  GET_PROMOTIONS_MERCHANT_FAILED: 'GET_PROMOTIONS_MERCHANT_FAILED',

  GET_PROMOTIONS_MERCHANT_FILTER_REQUEST: 'GET_PROMOTIONS_MERCHANT_FILTER_REQUEST',
  GET_PROMOTIONS_MERCHANT_FILTER_SUCCESS: 'GET_PROMOTIONS_MERCHANT_FILTER_SUCCESS',
  GET_PROMOTIONS_MERCHANT_FILTER_FAILED: 'GET_PROMOTIONS_MERCHANT_FILTER_FAILED',

  GET_PROMOTIONS_MERCHANT_FILTER_PAGINATE_REQUEST: 'GET_PROMOTIONS_MERCHANT_FILTER_PAGINATE_REQUEST',
  GET_PROMOTIONS_MERCHANT_FILTER_PAGINATE_SUCCESS: 'GET_PROMOTIONS_MERCHANT_FILTER_PAGINATE_SUCCESS',
  GET_PROMOTIONS_MERCHANT_FILTER_PAGINATE_FAILED: 'GET_PROMOTIONS_MERCHANT_FILTER_PAGINATE_FAILED',

  GET_PROMOTIONS_COMPANY_PAGINATE_REQUEST: 'GET_PROMOTIONS_COMPANY_PAGINATE_REQUEST',
  GET_PROMOTIONS_COMPANY_PAGINATE_SUCCESS: 'GET_PROMOTIONS_COMPANY_PAGINATE_SUCCESS',
  GET_PROMOTIONS_COMPANY_PAGINATE_FAILED: 'GET_PROMOTIONS_COMPANY_PAGINATE_FAILED',

  GET_PROMOTIONS_MERCHANT_PAGINATE_REQUEST: 'GET_PROMOTIONS_MERCHANT_PAGINATE_REQUEST',
  GET_PROMOTIONS_MERCHANT_PAGINATE_SUCCESS: 'GET_PROMOTIONS_MERCHANT_PAGINATE_SUCCESS',
  GET_PROMOTIONS_MERCHANT_PAGINATE_FAILED: 'GET_PROMOTIONS_MERCHANT_PAGINATE_FAILED',

  ADD_PROMOTIONS_MERCHANT_REQUEST: 'ADD_PROMOTIONS_MERCHANT_REQUEST',
  ADD_PROMOTIONS_MERCHANT_SUCCESS: 'ADD_PROMOTIONS_MERCHANT_SUCCESS',
  ADD_PROMOTIONS_MERCHANT_FAILED: 'ADD_PROMOTIONS_MERCHANT_FAILED',

  EDIT_PROMOTIONS_MERCHANT_REQUEST: 'EDIT_PROMOTIONS_MERCHANT_REQUEST',
  EDIT_PROMOTIONS_MERCHANT_SUCCESS: 'EDIT_PROMOTIONS_MERCHANT_SUCCESS',
  EDIT_PROMOTIONS_MERCHANT_FAILED: 'EDIT_PROMOTIONS_MERCHANT_FAILED',

  EDIT_STATE_PROMOTIONS_MERCHANT_REQUEST: 'EDIT_STATE_PROMOTIONS_MERCHANT_REQUEST',
  EDIT_STATE_PROMOTIONS_MERCHANT_SUCCESS: 'EDIT_STATE_PROMOTIONS_MERCHANT_SUCCESS',
  EDIT_STATE_PROMOTIONS_MERCHANT_FAILED: 'EDIT_STATE_PROMOTIONS_MERCHANT_FAILED',

  EDIT_PUBLISH_PROMOTIONS_MERCHANT_REQUEST: 'EDIT_PUBLISH_PROMOTIONS_MERCHANT_REQUEST',
  EDIT_PUBLISH_PROMOTIONS_MERCHANT_SUCCESS: 'EDIT_PUBLISH_PROMOTIONS_MERCHANT_SUCCESS',
  EDIT_PUBLISH_PROMOTIONS_MERCHANT_FAILED: 'EDIT_PUBLISH_PROMOTIONS_MERCHANT_FAILED',

  DELETE_PROMOTIONS_MERCHANT_REQUEST: 'DELETE_PROMOTIONS_MERCHANT_REQUEST',
  DELETE_PROMOTIONS_MERCHANT_SUCCESS: 'DELETE_PROMOTIONS_MERCHANT_SUCCESS',
  DELETE_PROMOTIONS_MERCHANT_FAILED: 'DELETE_PROMOTIONS_MERCHANT_FAILED',

  ACCEPT_STATE_PROMOTIONS_MERCHANT_REQUEST: 'ACCEPT_STATE_PROMOTIONS_MERCHANT_REQUEST',
  ACCEPT_STATE_PROMOTIONS_MERCHANT_SUCCESS: 'ACCEPT_STATE_PROMOTIONS_MERCHANT_SUCCESS',
  ACCEPT_STATE_PROMOTIONS_MERCHANT_FAILED: 'ACCEPT_STATE_PROMOTIONS_MERCHANT_FAILED',

  GET_SALES_REPORTS_MERCHANT_REQUEST: 'GET_SALES_REPORTS_MERCHANT_REQUEST',
  GET_SALES_REPORTS_MERCHANT_SUCCESS: 'GET_SALES_REPORTS_MERCHANT_SUCCESS',
  GET_SALES_REPORTS_MERCHANT_FAILED: 'GET_SALES_REPORTS_MERCHANT_FAILED',

  GET_SALES_REPORTS_MERCHANT_FILTER_REQUEST: 'GET_SALES_REPORTS_MERCHANT_FILTER_REQUEST',
  GET_SALES_REPORTS_MERCHANT_FILTER_SUCCESS: 'GET_SALES_REPORTS_MERCHANT_FILTER_SUCCESS',
  GET_SALES_REPORTS_MERCHANT_FILTER_FAILED: 'GET_SALES_REPORTS_MERCHANT_FILTER_FAILED',

  GET_SALES_REPORTS_MERCHANT_PAGINATE_REQUEST: 'GET_SALES_REPORTS_MERCHANT_PAGINATE_REQUEST',
  GET_SALES_REPORTS_MERCHANT_PAGINATE_SUCCESS: 'GET_SALES_REPORTS_MERCHANT_PAGINATE_SUCCESS',
  GET_SALES_REPORTS_MERCHANT_PAGINATE_FAILED: 'GET_SALES_REPORTS_MERCHANT_PAGINATE_FAILED',

  GET_SALES_REPORTS_MERCHANT_PAGINATE_FILTER_REQUEST: 'GET_SALES_REPORTS_MERCHANT_PAGINATE_FILTER_REQUEST',
  GET_SALES_REPORTS_MERCHANT_PAGINATE_FILTER_SUCCESS: 'GET_SALES_REPORTS_MERCHANT_PAGINATE_FILTER_SUCCESS',
  GET_SALES_REPORTS_MERCHANT_PAGINATE_FILTER_FAILED: 'GET_SALES_REPORTS_MERCHANT_PAGINATE_FILTER_FAILED',

  CONFIRM_SALES_REPORTS_MERCHANT_REQUEST: 'CONFIRM_SALES_REPORTS_MERCHANT_REQUEST',
  CONFIRM_SALES_REPORTS_MERCHANT_SUCCESS: 'CONFIRM_SALES_REPORTS_MERCHANT_SUCCESS',
  CONFIRM_SALES_REPORTS_MERCHANT_FAILED: 'CONFIRM_SALES_REPORTS_MERCHANT_FAILED',

  REQUEST_SALES_REPORTS_MERCHANT_REQUEST: 'REQUEST_SALES_REPORTS_MERCHANT_REQUEST',
  REQUEST_SALES_REPORTS_MERCHANT_SUCCESS: 'REQUEST_SALES_REPORTS_MERCHANT_SUCCESS',
  REQUEST_SALES_REPORTS_MERCHANT_FAILED: 'REQUEST_SALES_REPORTS_MERCHANT_FAILED',

  GET_CODE_SALES_REPORTS_MERCHANT_REQUEST: 'GET_CODE_SALES_REPORTS_MERCHANT_REQUEST',
  GET_CODE_SALES_REPORTS_MERCHANT_SUCCESS: 'GET_CODE_SALES_REPORTS_MERCHANT_SUCCESS',
  GET_CODE_SALES_REPORTS_MERCHANT_FAILED: 'GET_CODE_SALES_REPORTS_MERCHANT_FAILED',

  EDIT_DESCRIPTION_SALES_REPORTS_MERCHANT_REQUEST: 'EDIT_DESCRIPTION_SALES_REPORTS_MERCHANT_REQUEST',
  EDIT_DESCRIPTION_SALES_REPORTS_MERCHANT_SUCCESS: 'EDIT_DESCRIPTION_SALES_REPORTS_MERCHANT_SUCCESS',
  EDIT_DESCRIPTION_SALES_REPORTS_MERCHANT_FAILED: 'EDIT_DESCRIPTION_SALES_REPORTS_MERCHANT_FAILED',

  GET_INSTALLMENT_COMPANY_REQUEST: 'GET_INSTALLMENT_COMPANY_REQUEST',
  GET_INSTALLMENT_COMPANY_SUCCESS: 'GET_INSTALLMENT_COMPANY_SUCCESS',
  GET_INSTALLMENT_COMPANY_FAILED: 'GET_INSTALLMENT_COMPANY_FAILED',

  GET_INSTALLMENT_COMPANY_PAGINATE_REQUEST: 'GET_INSTALLMENT_COMPANY_PAGINATE_REQUEST',
  GET_INSTALLMENT_COMPANY_PAGINATE_SUCCESS: 'GET_INSTALLMENT_COMPANY_PAGINATE_SUCCESS',
  GET_INSTALLMENT_COMPANY_PAGINATE_FAILED: 'GET_INSTALLMENT_COMPANY_PAGINATE_FAILED',

  FILTER_INSTALLMENT_COMPANY_REQUEST: 'FILTER_INSTALLMENT_COMPANY_REQUEST',
  FILTER_INSTALLMENT_COMPANY_SUCCESS: 'FILTER_INSTALLMENT_COMPANY_SUCCESS',
  FILTER_INSTALLMENT_COMPANY_FAILED: 'FILTER_INSTALLMENT_COMPANY_FAILED',

  FILTER_INSTALLMENT_COMPANY_PAGINATION_REQUEST: 'FILTER_INSTALLMENT_COMPANY_PAGINATION_REQUEST',
  FILTER_INSTALLMENT_COMPANY_PAGINATION_SUCCESS: 'FILTER_INSTALLMENT_COMPANY_PAGINATION_SUCCESS',
  FILTER_INSTALLMENT_COMPANY_PAGINATION_FAILED: 'FILTER_INSTALLMENT_COMPANY_PAGINATION_FAILED',

  GET_MERCHANT_SALES_REQUEST: 'GET_MERCHANT_SALES_REQUEST',
  GET_MERCHANT_SALES_SUCCESS: 'GET_MERCHANT_SALES_SUCCESS',
  GET_MERCHANT_SALES_FAILED: 'GET_MERCHANT_SALES_FAILED',

  SEND_CODE_SALES_REQUEST: 'SEND_CODE_SALES_REQUEST',
  SEND_CODE_SALES_SUCCESS: 'SEND_CODE_SALES_SUCCESS',
  SEND_CODE_SALES_FAILED: 'SEND_CODE_SALES_FAILED',

  GET_MOBILE_SALES_REQUEST: 'GET_MOBILE_SALES_REQUEST',
  GET_MOBILE_SALES_SUCCESS: 'GET_MOBILE_SALES_SUCCESS',
  GET_MOBILE_SALES_FAILED: 'GET_MOBILE_SALES_FAILED',

  GET_CARD_SALES_REQUEST: 'GET_CARD_SALES_REQUEST',
  GET_CARD_SALES_SUCCESS: 'GET_CARD_SALES_SUCCESS',
  GET_CARD_SALES_FAILED: 'GET_CARD_SALES_FAILED',

  GET_CARD_SALES_COMPANY_REQUEST: 'GET_CARD_SALES_COMPANY_REQUEST',
  GET_CARD_SALES_COMPANY_SUCCESS: 'GET_CARD_SALES_COMPANY_SUCCESS',
  GET_CARD_SALES_COMPANY_FAILED: 'GET_CARD_SALES_COMPANY_FAILED',

  GET_PROMOTION_LIST_REQUEST: 'GET_PROMOTION_LIST_REQUEST',
  GET_PROMOTION_LIST_SUCCESS: 'GET_PROMOTION_LIST_SUCCESS',
  GET_PROMOTION_LIST_FAILED: 'GET_PROMOTION_LIST_FAILED',

  SET_CONTRACT_DETAILS: 'SET_CONTRACT_DETAILS',
  REMOVE_CARDS: 'REMOVE_CARDS',
  SET_CREDIT: 'SET_CREDIT',

  GET_PROFILE_COMPANY_REQUEST: 'GET_PROFILE_COMPANY_REQUEST',
  GET_PROFILE_COMPANY_SUCCESS: 'GET_PROFILE_COMPANY_SUCCESS',
  GET_PROFILE_COMPANY_FAILED: 'GET_PROFILE_COMPANY_FAILED',

  SAVE_PROFILE_COMPANY_REQUEST: 'SAVE_PROFILE_COMPANY_REQUEST',
  SAVE_PROFILE_COMPANY_SUCCESS: 'SAVE_PROFILE_COMPANY_SUCCESS',
  SAVE_PROFILE_COMPANY_FAILED: 'SAVE_PROFILE_COMPANY_FAILED',

  GET_MERCHANT_COMPANY_REQUEST: 'GET_MERCHANT_COMPANY_REQUEST',
  GET_MERCHANT_COMPANY_SUCCESS: 'GET_MERCHANT_COMPANY_SUCCESS',
  GET_MERCHANT_COMPANY_FAILED: 'GET_MERCHANT_COMPANY_FAILED',

  GET_MERCHANT_COMPANY_PAGINATE_REQUEST: 'GET_MERCHANT_COMPANY_PAGINATE_REQUEST',
  GET_MERCHANT_COMPANY_PAGINATE_SUCCESS: 'GET_MERCHANT_COMPANY_PAGINATE_SUCCESS',
  GET_MERCHANT_COMPANY_PAGINATE_FAILED: 'GET_MERCHANT_COMPANY_PAGINATE_FAILED',

  GET_MERCHANT_COMPANY_FILTER_REQUEST: 'GET_MERCHANT_COMPANY_FILTER_REQUEST',
  GET_MERCHANT_COMPANY_FILTER_SUCCESS: 'GET_MERCHANT_COMPANY_FILTER_SUCCESS',
  GET_MERCHANT_COMPANY_FILTER_FAILED: 'GET_MERCHANT_COMPANY_FILTER_FAILED',

  GET_MERCHANT_COMPANY_FILTER_PAGINATE_REQUEST: 'GET_MERCHANT_COMPANY_FILTER_PAGINATE_REQUEST',
  GET_MERCHANT_COMPANY_FILTER_PAGINATE_SUCCESS: 'GET_MERCHANT_COMPANY_FILTER_PAGINATE_SUCCESS',
  GET_MERCHANT_COMPANY_FILTER_PAGINATE_FAILED: 'GET_MERCHANT_COMPANY_FILTER_PAGINATE_FAILED',

  SET_MERCHANT_STATE_REQUEST: 'SET_MERCHANT_STATE_REQUEST',
  SET_MERCHANT_STATE_SUCCESS: 'SET_MERCHANT_STATE_SUCCESS',
  SET_MERCHANT_STATE_FAILED: 'SET_MERCHANT_STATE_FAILED',

  DELETE_MERCHANT_REQUEST: 'DELETE_MERCHANT_REQUEST',
  DELETE_MERCHANT_SUCCESS: 'DELETE_MERCHANT_SUCCESS',
  DELETE_MERCHANT_FAILED: 'DELETE_MERCHANT_FAILED',

  EDIT_FINANCE_REQUEST: 'EDIT_FINANCE_REQUEST',
  EDIT_FINANCE_SUCCESS: 'EDIT_FINANCE_SUCCESS',
  EDIT_FINANCE_FAILED: 'EDIT_FINANCE_FAILED',

  EDIT_USER_REQUEST: 'EDIT_USER_REQUEST',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILED: 'EDIT_USER_FAILED',

  ADD_MERCHANT_REQUEST: 'ADD_MERCHANT_REQUEST',
  ADD_MERCHANT_SUCCESS: 'ADD_MERCHANT_SUCCESS',
  ADD_MERCHANT_FAILED: 'ADD_MERCHANT_FAILED',

  EDIT_MERCHANT_REQUEST: 'EDIT_MERCHANT_REQUEST',
  EDIT_MERCHANT_SUCCESS: 'EDIT_MERCHANT_SUCCESS',
  EDIT_MERCHANT_FAILED: 'EDIT_MERCHANT_FAILED',

  REMOVE_CREDIT: 'REMOVE_CREDIT',

  GET_ORG_MANAGEMENT_COMPANY_REQUEST: 'GET_ORG_MANAGEMENT_COMPANY_REQUEST',
  GET_ORG_MANAGEMENT_COMPANY_SUCCESS: 'GET_ORG_MANAGEMENT_COMPANY_SUCCESS',
  GET_ORG_MANAGEMENT_COMPANY_FAILED: 'GET_ORG_MANAGEMENT_COMPANY_FAILED',

  GET_ORG_MANAGEMENT_COMPANY_PAGINATE_REQUEST: 'GET_ORG_MANAGEMENT_COMPANY_PAGINATE_REQUEST',
  GET_ORG_MANAGEMENT_COMPANY_PAGINATE_SUCCESS: 'GET_ORG_MANAGEMENT_COMPANY_PAGINATE_SUCCESS',
  GET_ORG_MANAGEMENT_COMPANY_PAGINATE_FAILED: 'GET_ORG_MANAGEMENT_COMPANY_PAGINATE_FAILED',

  FILTER_ORG_MANAGEMENT_COMPANY_REQUEST: 'FILTER_ORG_MANAGEMENT_COMPANY_REQUEST',
  FILTER_ORG_MANAGEMENT_COMPANY_SUCCESS: 'FILTER_ORG_MANAGEMENT_COMPANY_SUCCESS',
  FILTER_ORG_MANAGEMENT_COMPANY_FAILED: 'FILTER_ORG_MANAGEMENT_COMPANY_FAILED',

  FILTER_ORG_MANAGEMENT_COMPANY_PAGINATE_REQUEST: 'FILTER_ORG_MANAGEMENT_COMPANY_PAGINATE_REQUEST',
  FILTER_ORG_MANAGEMENT_COMPANY_PAGINATE_SUCCESS: 'FILTER_ORG_MANAGEMENT_COMPANY_PAGINATE_SUCCESS',
  FILTER_ORG_MANAGEMENT_COMPANY_PAGINATE_FAILED: 'FILTER_ORG_MANAGEMENT_COMPANY_PAGINATE_FAILED',

  GET_GRID_COMPANY_CONTRACT_REQUEST: 'GET_GRID_COMPANY_CONTRACT_REQUEST',
  GET_GRID_COMPANY_CONTRACT_SUCCESS: 'GET_GRID_COMPANY_CONTRACT_SUCCESS',
  GET_GRID_COMPANY_CONTRACT_FAILED: 'GET_GRID_COMPANY_CONTRACT_FAILED',

  GET_GRID_COMPANY_CONTRACT_PAGINATE_REQUEST: 'GET_GRID_COMPANY_CONTRACT_PAGINATE_REQUEST',
  GET_GRID_COMPANY_CONTRACT_PAGINATE_SUCCESS: 'GET_GRID_COMPANY_CONTRACT_PAGINATE_SUCCESS',
  GET_GRID_COMPANY_CONTRACT_PAGINATE_FAILED: 'GET_GRID_COMPANY_CONTRACT_PAGINATE_FAILED',

  FILTER_COMPANY_CONTRACT_GRID_REQUEST: 'FILTER_COMPANY_CONTRACT_GRID_REQUEST',
  FILTER_COMPANY_CONTRACT_GRID_SUCCESS: 'FILTER_COMPANY_CONTRACT_GRID_SUCCESS',
  FILTER_COMPANY_CONTRACT_GRID_FAILED: 'FILTER_COMPANY_CONTRACT_GRID_FAILED',

  FILTER_COMPANY_CONTRACT_GRID_PAGINATION_REQUEST: 'FILTER_COMPANY_CONTRACT_GRID_PAGINATION_REQUEST',
  FILTER_COMPANY_CONTRACT_GRID_PAGINATION_SUCCESS: 'FILTER_COMPANY_CONTRACT_GRID_PAGINATION_SUCCESS',
  FILTER_COMPANY_CONTRACT_GRID_PAGINATION_FAILED: 'FILTER_COMPANY_CONTRACT_GRID_PAGINATION_FAILED',

  EDIT_COMPANY_CONTRACT_REQUEST: 'EDIT_COMPANY_CONTRACT_REQUEST',
  EDIT_COMPANY_CONTRACT_SUCCESS: 'EDIT_COMPANY_CONTRACT_SUCCESS',
  EDIT_COMPANY_CONTRACT_FAILED: 'EDIT_COMPANY_CONTRACT_FAILED',

  ADD_COMPANY_CONTRACT_REQUEST: 'ADD_COMPANY_CONTRACT_REQUEST',
  ADD_COMPANY_CONTRACT_SUCCESS: 'ADD_COMPANY_CONTRACT_SUCCESS',
  ADD_COMPANY_CONTRACT_FAILED: 'ADD_COMPANY_CONTRACT_FAILED',

  EDIT_STATE_COMPANY_CONTRACT_REQUEST: 'EDIT_STATE_COMPANY_CONTRACT_REQUEST',
  EDIT_STATE_COMPANY_CONTRACT_SUCCESS: 'EDIT_STATE_COMPANY_CONTRACT_SUCCESS',
  EDIT_STATE_COMPANY_CONTRACT_FAILED: 'EDIT_STATE_COMPANY_CONTRACT_FAILED',

  ACCEPT_STATE_COMPANY_CONTRACT_REQUEST: 'ACCEPT_STATE_COMPANY_CONTRACT_REQUEST',
  ACCEPT_STATE_COMPANY_CONTRACT_SUCCESS: 'ACCEPT_STATE_COMPANY_CONTRACT_SUCCESS',
  ACCEPT_STATE_COMPANY_CONTRACT_FAILED: 'ACCEPT_STATE_COMPANY_CONTRACT_FAILED',

  DELETE_COMPANY_CONTRACT_REQUEST: 'DELETE_COMPANY_CONTRACT_REQUEST',
  DELETE_COMPANY_CONTRACT_SUCCESS: 'DELETE_COMPANY_CONTRACT_SUCCESS',
  DELETE_COMPANY_CONTRACT_FAILED: 'DELETE_COMPANY_CONTRACT_FAILED',

  ADD_ORG_MANAGEMENT_COMPANY_REQUEST: 'ADD_ORG_MANAGEMENT_COMPANY_REQUEST',
  ADD_ORG_MANAGEMENT_COMPANY_SUCCESS: 'ADD_ORG_MANAGEMENT_COMPANY_SUCCESS',
  ADD_ORG_MANAGEMENT_COMPANY_FAILED: 'ADD_ORG_MANAGEMENT_COMPANY_FAILED',

  EDIT_ORG_MANAGEMENT_COMPANY_REQUEST: 'EDIT_ORG_MANAGEMENT_COMPANY_REQUEST',
  EDIT_ORG_MANAGEMENT_COMPANY_SUCCESS: 'EDIT_ORG_MANAGEMENT_COMPANY_SUCCESS',
  EDIT_ORG_MANAGEMENT_COMPANY_FAILED: 'EDIT_ORG_MANAGEMENT_COMPANY_FAILED',

  EDIT_STATE_ORG_MANAGEMENT_COMPANY_REQUEST: 'EDIT_STATE_ORG_MANAGEMENT_COMPANY_REQUEST',
  EDIT_STATE_ORG_MANAGEMENT_COMPANY_SUCCESS: 'EDIT_STATE_ORG_MANAGEMENT_COMPANY_SUCCESS',
  EDIT_STATE_ORG_MANAGEMENT_COMPANY_FAILED: 'EDIT_STATE_ORG_MANAGEMENT_COMPANY_FAILED',

  DELETE_ORG_MANAGEMENT_COMPANY_REQUEST: 'DELETE_ORG_MANAGEMENT_COMPANY_REQUEST',
  DELETE_ORG_MANAGEMENT_COMPANY_SUCCESS: 'DELETE_ORG_MANAGEMENT_COMPANY_SUCCESS',
  DELETE_ORG_MANAGEMENT_COMPANY_FAILED: 'DELETE_ORG_MANAGEMENT_COMPANY_FAILED',

  EDIT_FINANCE_COMPANY_REQUEST: 'EDIT_FINANCE_COMPANY_REQUEST',
  EDIT_FINANCE_COMPANY_SUCCESS: 'EDIT_FINANCE_COMPANY_SUCCESS',
  EDIT_FINANCE_COMPANY_FAILED: 'EDIT_FINANCE_COMPANY_FAILED',

  GET_DASHBOARD_COMPANY_REQUEST: 'GET_DASHBOARD_COMPANY_REQUEST',
  GET_DASHBOARD_COMPANY_SUCCESS: 'GET_DASHBOARD_COMPANY_SUCCESS',
  GET_DASHBOARD_COMPANY_FAILED: 'GET_DASHBOARD_COMPANY_FAILED',

  CONFIRM_PURCHACE_REPORTS_REQUEST: 'CONFIRM_PURCHACE_REPORTS_REQUEST',
  CONFIRM_PURCHACE_REPORTS_SUCCESS: 'CONFIRM_PURCHACE_REPORTST_SUCCESS',
  CONFIRM_PURCHACE_REPORTS_FAILED: 'CONFIRM_PURCHACE_REPORTS_FAILED',

  REQUEST_PURCHACE_REPORTS_REQUEST: 'REQUEST_PURCHACE_REPORTS_REQUEST',
  REQUEST_PURCHACE_REPORTS_SUCCESS: 'REQUEST_PURCHACE_REPORTST_SUCCESS',
  REQUEST_PURCHACE_REPORTS_FAILED: 'REQUEST_PURCHACE_REPORTS_FAILED',

  GET_CODE_PURCHACE_REPORTS_REQUEST: 'GET_CODE_PURCHACE_REPORTS_REQUEST',
  GET_CODE_PURCHACE_REPORTS_SUCCESS: 'GET_CODE_PURCHACE_REPORTS_SUCCESS',
  GET_CODE_PURCHACE_REPORTS_FAILED: 'GET_CODE_PURCHACE_REPORTS_FAILED',

  GET_MOBILE_NUMBER_COMPANY_REQUEST: 'GET_MOBILE_NUMBER_COMPANY_REQUEST',
  GET_MOBILE_NUMBER_COMPANY_SUCCESS: 'GET_MOBILE_NUMBER_COMPANY_SUCCESS',
  GET_MOBILE_NUMBER_COMPANY_FAILED: 'GET_MOBILE_NUMBER_COMPANY_FAILED',

  FILTER_GRID_CONTRACT_REQUEST: 'FILTER_GRID_CONTRACT_REQUEST',
  FILTER_GRID_CONTRACT_SUCCESS: 'FILTER_GRID_CONTRACT_SUCCESS',
  FILTER_GRID_CONTRACT_FAILED: 'FILTER_GRID_CONTRACT_FAILED',

  FILTER_GRID_CONTRACT_PAGING_REQUEST: 'FILTER_GRID_CONTRACT_PAGING_REQUEST',
  FILTER_GRID_CONTRACT_PAGING_SUCCESS: 'FILTER_GRID_CONTRACT_PAGING_SUCCESS',
  FILTER_GRID_CONTRACT_PAGING_FAILED: 'FILTER_GRID_CONTRACT_PAGING_FAILED',

  SEARCH_MOBILE_NUMBER_REQUEST: 'SEARCH_MOBILE_NUMBER_REQUEST',
  SEARCH_MOBILE_NUMBER_SUCCESS: 'SEARCH_MOBILE_NUMBER_SUCCESS',
  SEARCH_MOBILE_NUMBER_FAILED: 'SEARCH_MOBILE_NUMBER_FAILED',

  LIST_GRID_PURCHASE_ORG_REQUEST: 'LIST_GRID_PURCHASE_ORG_REQUEST',
  LIST_GRID_PURCHASE_ORG_SUCCESS: 'LIST_GRID_PURCHASE_ORG_SUCCESS',
  LIST_GRID_PURCHASE_ORG_FAILED: 'LIST_GRID_PURCHASE_ORG_FAILED',

  LIST_GRID_PURCHASE_ORG_FILTER_REQUEST: 'LIST_GRID_PURCHASE_ORG_FILTER_REQUEST',
  LIST_GRID_PURCHASE_ORG_FILTER_SUCCESS: 'LIST_GRID_PURCHASE_ORG_FILTER_SUCCESS',
  LIST_GRID_PURCHASE_ORG_FILTER_FAILED: 'LIST_GRID_PURCHASE_ORG_FILTER_FAILED',

  LIST_GRID_PURCHASE_ORG_FILTER_PAGING_REQUEST: 'LIST_GRID_PURCHASE_ORG_FILTER_PAGING_REQUEST',
  LIST_GRID_PURCHASE_ORG_FILTER_PAGING_SUCCESS: 'LIST_GRID_PURCHASE_ORG_FILTER_PAGING_SUCCESS',
  LIST_GRID_PURCHASE_ORG_FILTER_PAGING_FAILED: 'LIST_GRID_PURCHASE_ORG_FILTER_PAGING_FAILED',

  LIST_GRID_PURCHASE_ORG_PAGINATE_REQUEST: 'LIST_GRID_PURCHASE_ORG_PAGINATE_REQUEST',
  LIST_GRID_PURCHASE_ORG_PAGINATE_SUCCESS: 'LIST_GRID_PURCHASE_ORG_PAGINATE_SUCCESS',
  LIST_GRID_PURCHASE_ORG_PAGINATE_FAILED: 'LIST_GRID_PURCHASE_ORG_PAGINATE_FAILED',

  REMEMBER_ME: 'REMEMBER_ME',

  RESTORE_INFO_REQUEST: 'RESTORE_INFO_REQUEST',
  RESTORE_INFO_SUCCESS: 'RESTORE_INFO_SUCCESS',
  RESTORE_INFO_FAILED: 'RESTORE_INFO_FAILED',

  SAVE_USER_INFO_COMPANY_REQUEST: 'SAVE_USER_INFO_COMPANY_REQUEST',
  SAVE_USER_INFO_COMPANY_SUCCESS: 'SAVE_USER_INFO_COMPANY_SUCCESS',
  SAVE_USER_INFO_COMPANY_FAILED: 'SAVE_USER_INFO_COMPANY_FAILED',

  LIST_COMPANY_USER_MANAGEMENT_REQUEST: 'LIST_COMPANY_USER_MANAGEMENT_REQUEST',
  LIST_COMPANY_USER_MANAGEMENT_SUCCESS: 'LIST_COMPANY_USER_MANAGEMENT_SUCCESS',
  LIST_COMPANY_USER_MANAGEMENT_FAILED: 'LIST_COMPANY_USER_MANAGEMENT_FAILED',

  LIST_COMPANY_USER_MANAGEMENT_PAGINATE_REQUEST: 'LIST_COMPANY_USER_MANAGEMENT_PAGINATE_REQUEST',
  LIST_COMPANY_USER_MANAGEMENT_PAGINATE_SUCCESS: 'LIST_COMPANY_USER_MANAGEMENT_PAGINATE_SUCCESS',
  LIST_COMPANY_USER_MANAGEMENT_PAGINATE_FAILED: 'LIST_COMPANY_USER_MANAGEMENT_PAGINATE_FAILED',

  ADD_USER_MANAGEMENT_COMPANY_REQUEST: 'ADD_USER_MANAGEMENT_COMPANY_REQUEST',
  ADD_USER_MANAGEMENT_COMPANY_SUCCESS: 'ADD_USER_MANAGEMENT_COMPANY_SUCCESS',
  ADD_USER_MANAGEMENT_COMPANY_FAILED: 'ADD_USER_MANAGEMENT_COMPANY_FAILED',

  EDIT_USER_MANAGEMENT_COMPANY_REQUEST: 'EDIT_USER_MANAGEMENT_COMPANY_REQUEST',
  EDIT_USER_MANAGEMENT_COMPANY_SUCCESS: 'EDIT_USER_MANAGEMENT_COMPANY_SUCCESS',
  EDIT_USER_MANAGEMENT_COMPANY_FAILED: 'EDIT_USER_MANAGEMENT_COMPANY_FAILED',

  DELETE_USER_MANAGEMENT_COMPANY_REQUEST: 'DELETE_USER_MANAGEMENT_COMPANY_REQUEST',
  DELETE_USER_MANAGEMENT_COMPANY_SUCCESS: 'DELETE_USER_MANAGEMENT_COMPANY_SUCCESS',
  DELETE_USER_MANAGEMENT_COMPANY_FAILED: 'DELETE_USER_MANAGEMENT_COMPANY_FAILED',

  ADD_ACCESS_USER_MANAGEMENT_COMPANY_REQUEST: 'ADD_ACCESS_USER_MANAGEMENT_COMPANY_REQUEST',
  ADD_ACCESS_USER_MANAGEMENT_COMPANY_SUCCESS: 'ADD_ACCESS_USER_MANAGEMENT_COMPANY_SUCCESS',
  ADD_ACCESS_USER_MANAGEMENT_COMPANY_FAILED: 'ADD_ACCESS_USER_MANAGEMENT_COMPANY_FAILED',

  EDIT_ACCESS_USER_MANAGEMENT_COMPANY_REQUEST: 'EDIT_ACCESS_USER_MANAGEMENT_COMPANY_REQUEST',
  EDIT_ACCESS_USER_MANAGEMENT_COMPANY_SUCCESS: 'EDIT_ACCESS_USER_MANAGEMENT_COMPANY_SUCCESS',
  EDIT_ACCESS_USER_MANAGEMENT_COMPANY_FAILED: 'EDIT_ACCESS_USER_MANAGEMENT_COMPANY_FAILED',

  DELETE_ACCESS_USER_MANAGEMENT_COMPANY_REQUEST: 'DELETE_ACCESS_USER_MANAGEMENT_COMPANY_REQUEST',
  DELETE_ACCESS_USER_MANAGEMENT_COMPANY_SUCCESS: 'DELETE_ACCESS_USER_MANAGEMENT_COMPANY_SUCCESS',
  DELETE_ACCESS_USER_MANAGEMENT_COMPANY_FAILED: 'DELETE_ACCESS_USER_MANAGEMENT_COMPANY_FAILED',

  LIST_FILTER_COMPANY_USER_MANAGEMENT_REQUEST: 'LIST_FILTER_COMPANY_USER_MANAGEMENT_REQUEST',
  LIST_FILTER_COMPANY_USER_MANAGEMENT_SUCCESS: 'LIST_FILTER_COMPANY_USER_MANAGEMENT_SUCCESS',
  LIST_FILTER_COMPANY_USER_MANAGEMENT_FAILED: 'LIST_FILTER_COMPANY_USER_MANAGEMENT_FAILED',

  LIST_FILTER_COMPANY_USER_MANAGEMENT_PAGINATION_REQUEST: 'LIST_FILTER_COMPANY_USER_MANAGEMENT_PAGINATION_REQUEST',
  LIST_FILTER_COMPANY_USER_MANAGEMENT_PAGINATION_SUCCESS: 'LIST_FILTER_COMPANY_USER_MANAGEMENT_PAGINATION_SUCCESS',
  LIST_FILTER_COMPANY_USER_MANAGEMENT_PAGINATION_FAILED: 'LIST_FILTER_COMPANY_USER_MANAGEMENT_PAGINATION_FAILED',

  OTP_CODE_FINANCE_ORGANIZATION_PROFILE_REQUEST: 'OTP_CODE_FINANCE_ORGANIZATION_PROFILE_REQUEST',
  OTP_CODE_FINANCE_ORGANIZATION_PROFILE_SUCCESS: 'OTP_CODE_FINANCE_ORGANIZATION_PROFILE_SUCCESS',
  OTP_CODE_FINANCE_ORGANIZATION_PROFILE_FAILED: 'OTP_CODE_FINANCE_ORGANIZATION_PROFILE_FAILED',

  SAVE_FINANCE_ORGANIZATION_PROFILE_REQUEST: 'SAVE_FINANCE_ORGANIZATION_PROFILE_REQUEST',
  SAVE_FINANCE_ORGANIZATION_PROFILE_SUCCESS: 'SAVE_FINANCE_ORGANIZATION_PROFILE_SUCCESS',
  SAVE_FINANCE_ORGANIZATION_PROFILE_FAILED: 'SAVE_FINANCE_ORGANIZATION_PROFILE_FAILED',

  OTP_CODE_FINANCE_MERCHANT_PROFILE_REQUEST: 'OTP_CODE_FINANCE_MERCHANT_PROFILE_REQUEST',
  OTP_CODE_FINANCE_MERCHANT_PROFILE_SUCCESS: 'OTP_CODE_FINANCE_MERCHANT_PROFILE_SUCCESS',
  OTP_CODE_FINANCE_MERCHANT_PROFILE_FAILED: 'OTP_CODE_FINANCE_MERCHANT_PROFILE_FAILED',

  SAVE_FINANCE_MERCHANT_PROFILE_REQUEST: 'SAVE_FINANCE_MERCHANT_PROFILE_REQUEST',
  SAVE_FINANCE_MERCHANT_PROFILE_SUCCESS: 'SAVE_FINANCE_MERCHANT_PROFILE_SUCCESS',
  SAVE_FINANCE_MERCHANT_PROFILE_FAILED: 'SAVE_FINANCE_MERCHANT_PROFILE_FAILED',

  GET_WORKFLOW_MERCHANT_COMPANY_REQUEST: 'GET_WORKFLOW_MERCHANT_COMPANY_REQUEST',
  GET_WORKFLOW_MERCHANT_COMPANY_SUCCESS: 'GET_WORKFLOW_MERCHANT_COMPANY_SUCCESS',
  GET_WORKFLOW_MERCHANT_COMPANY_FAILED: 'GET_WORKFLOW_MERCHANT_COMPANY_FAILED',

  GET_WORKFLOW_MERCHANT_COMPANY_PAGINATE_REQUEST: 'GET_WORKFLOW_MERCHANT_COMPANY_PAGINATE_REQUEST',
  GET_WORKFLOW_MERCHANT_COMPANY_PAGINATE_SUCCESS: 'GET_WORKFLOW_MERCHANT_COMPANY_PAGINATE_SUCCESS',
  GET_WORKFLOW_MERCHANT_COMPANY_PAGINATE_FAILED: 'GET_WORKFLOW_MERCHANT_COMPANY_PAGINATE_FAILED',

  DELETE_WORKFLOW_MERCHANT_REQUEST: 'DELETE_WORKFLOW_MERCHANT_REQUEST',
  DELETE_WORKFLOW_MERCHANT_SUCCESS: 'DELETE_WORKFLOW_MERCHANT_SUCCESS',
  DELETE_WORKFLOW_MERCHANT_FAILED: 'DELETE_WORKFLOW_MERCHANT_FAILED',

  DETAILES_WORKFLOW_MERCHANT_REQUEST: 'DETAILES_WORKFLOW_MERCHANT_REQUEST',
  DETAILES_WORKFLOW_MERCHANT_SUCCESS: 'DETAILES_WORKFLOW_MERCHANT_SUCCESS',
  DETAILES_WORKFLOW_MERCHANT_FAILED: 'DETAILES_WORKFLOW_MERCHANT_FAILED',

  SUBMIT_CHANGE_WORKFLOW_MERCHANT_REQUEST: 'SUBMIT_CHANGE_WORKFLOW_MERCHANT_REQUEST',
  SUBMIT_CHANGE_WORKFLOW_MERCHANT_SUCCESS: 'SUBMIT_CHANGE_WORKFLOW_MERCHANT_SUCCESS',
  SUBMIT_CHANGE_WORKFLOW_MERCHANT_FAILED: 'SUBMIT_CHANGE_WORKFLOW_MERCHANT_FAILED',

  ADD_REQUEST_WORKFLOW_MERCHANT_REQUEST: 'ADD_REQUEST_WORKFLOW_MERCHANT_REQUEST',
  ADD_REQUEST_WORKFLOW_MERCHANT_SUCCESS: 'ADD_REQUEST_WORKFLOW_MERCHANT_SUCCESS',
  ADD_REQUEST_WORKFLOW_MERCHANT_FAILED: 'ADD_REQUEST_WORKFLOW_MERCHANT_FAILED',

  SEND_CODE_WORKFLOW_MERCHANT_REQUEST: 'SEND_CODE_WORKFLOW_MERCHANT_REQUEST',
  SEND_CODE_WORKFLOW_MERCHANT_SUCCESS: 'SEND_CODE_WORKFLOW_MERCHANT_SUCCESS',
  SEND_CODE_WORKFLOW_MERCHANT_FAILED: 'SEND_CODE_WORKFLOW_MERCHANT_FAILED',

  UPLOAD_FILE_REQUEST: 'UPLOAD_FILE_REQUEST',
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  UPLOAD_FILE_FAILED: 'UPLOAD_FILE_FAILED',

  AVATAR_FILE_REQUEST: 'AVATAR_FILE_REQUEST',
  AVATAR_FILE_SUCCESS: 'AVATAR_FILE_SUCCESS',
  AVATAR_FILE_FAILED: 'AVATAR_FILE_FAILED',

  UPLOAD_FILE_ORGANIZATION_REQUEST: 'UPLOAD_FILE_ORGANIZATION_REQUEST',
  UPLOAD_FILE_ORGANIZATION_SUCCESS: 'UPLOAD_FILE_ORGANIZATION_SUCCESS',
  UPLOAD_FILE_ORGANIZATION_FAILED: 'UPLOAD_FILE_ORGANIZATION_FAILED',

  UPLOAD_FILE_INSTALLMENT_REQUEST: 'UPLOAD_FILE_INSTALLMENT_REQUEST',
  UPLOAD_FILE_INSTALLMENT_SUCCESS: 'UPLOAD_FILE_INSTALLMENT_SUCCESS',
  UPLOAD_FILE_INSTALLMENT_FAILED: 'UPLOAD_FILE_INSTALLMENT_FAILED',

  UPLOAD_FILE_MERCHANT_REQUEST: 'UPLOAD_FILE_MERCHANT_REQUEST',
  UPLOAD_FILE_MERCHANT_SUCCESS: 'UPLOAD_FILE_MERCHANT_SUCCESS',
  UPLOAD_FILE_MERCHANT_FAILED: 'UPLOAD_FILE_MERCHANT_FAILED',

  UPLOAD_FILE_COMPANY_REQUEST: 'UPLOAD_FILE_COMPANY_REQUEST',
  UPLOAD_FILE_COMPANY_SUCCESS: 'UPLOAD_FILE_COMPANY_SUCCESS',
  UPLOAD_FILE_COMPANY_FAILED: 'UPLOAD_FILE_COMPANY_FAILED',

  UPLOAD_FILE_PROMOTIONS_REQUEST: 'UPLOAD_FILE_PROMOTIONS_REQUEST',
  UPLOAD_FILE_PROMOTIONS_SUCCESS: 'UPLOAD_FILE_PROMOTIONS_SUCCESS',
  UPLOAD_FILE_PROMOTIONS_FAILED: 'UPLOAD_FILE_PROMOTIONS_FAILED',

  UPLOAD_FILE_ORG_ACCOUNTMANAGEMENT_REQUEST: 'UPLOAD_FILE_ORG_ACCOUNTMANAGEMENT_REQUEST',
  UPLOAD_FILE_ORG_ACCOUNTMANAGEMENT_SUCCESS: 'UPLOAD_FILE_ORG_ACCOUNTMANAGEMENT_SUCCESS',
  UPLOAD_FILE_ORG_ACCOUNTMANAGEMENT_FAILED: 'UPLOAD_FILE_ORG_ACCOUNTMANAGEMENT_FAILED'
}
export default actionTypes
